name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore ./src
      
    - name: Decode the Pfx
      shell: pwsh
      run: |
        $signing_keys_payload = [System.Convert]::FromBase64String("${{ secrets.SIGNING_KEY }}")
        $currentDirectory = Get-Location
        $certificatePath = Join-Path -Path $currentDirectory -ChildPath "key.snk"
        echo $certificatePath
        [IO.File]::WriteAllBytes("$certificatePath", $signing_keys_payload)          
        
    - name: Build
      run: dotnet build ./src --no-restore
      env:
        SignAssembly: true
        AssemblyOriginatorKeyFile: "/home/runner/work/asos-core-logicapps-cosmosconnector/asos-core-logicapps-cosmosconnector/key.snk"
      
    - name: Test
      run: dotnet test ./src --filter "FullyQualifiedName!~IntegrationTests" --no-build --verbosity normal
